In [1]:
import numpy as np

# actually generated by running the following code first
# np.set_printoptions(precision=5)
np.arange(25).reshape(5, 5) * np.pi

array([[ 0.        ,  3.14159265,  6.28318531,  9.42477796, 12.56637061],
       [15.70796327, 18.84955592, 21.99114858, 25.13274123, 28.27433388],
       [31.41592654, 34.55751919, 37.69911184, 40.8407045 , 43.98229715],
       [47.1238898 , 50.26548246, 53.40707511, 56.54866776, 59.69026042],
       [62.83185307, 65.97344573, 69.11503838, 72.25663103, 75.39822369]])

In [2]:
import numpy as np

# actually generated by running the following code first
# np.set_printoptions(threshold=4, edgeitems=2)
np.arange(25).reshape(5, 5) * np.pi

array([[ 0.        ,  3.14159265,  6.28318531,  9.42477796, 12.56637061],
       [15.70796327, 18.84955592, 21.99114858, 25.13274123, 28.27433388],
       [31.41592654, 34.55751919, 37.69911184, 40.8407045 , 43.98229715],
       [47.1238898 , 50.26548246, 53.40707511, 56.54866776, 59.69026042],
       [62.83185307, 65.97344573, 69.11503838, 72.25663103, 75.39822369]])

In [3]:
import numpy as np

# actually generated by running the following code first
# np.set_printoptions(precision=5, threshold=4, edgeitems=2)
np.arange(25).reshape(5, 5) * np.pi

array([[ 0.        ,  3.14159265,  6.28318531,  9.42477796, 12.56637061],
       [15.70796327, 18.84955592, 21.99114858, 25.13274123, 28.27433388],
       [31.41592654, 34.55751919, 37.69911184, 40.8407045 , 43.98229715],
       [47.1238898 , 50.26548246, 53.40707511, 56.54866776, 59.69026042],
       [62.83185307, 65.97344573, 69.11503838, 72.25663103, 75.39822369]])

In [4]:
import polars as pl

# actually generated by running the following code first
# pl.Config.set_tbl_rows(8)
penguins = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
str,str,f64,f64,i64,i64,str
"""Adelie""","""Torgersen""",39.1,18.7,181,3750,"""MALE"""
"""Adelie""","""Torgersen""",39.5,17.4,186,3800,"""FEMALE"""
"""Adelie""","""Torgersen""",40.3,18.0,195,3250,"""FEMALE"""
"""Adelie""","""Torgersen""",null,null,null,null,null
"""Adelie""","""Torgersen""",36.7,19.3,193,3450,"""FEMALE"""
…,…,…,…,…,…,…
"""Gentoo""","""Biscoe""",null,null,null,null,null
"""Gentoo""","""Biscoe""",46.8,14.3,215,4850,"""FEMALE"""
"""Gentoo""","""Biscoe""",50.4,15.7,222,5750,"""MALE"""


In [5]:
import polars as pl

# actually generated by running the following code first
# pl.Config.set_fmt_str_lengths(5)
penguins = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
str,str,f64,f64,i64,i64,str
"""Adelie""","""Torgersen""",39.1,18.7,181,3750,"""MALE"""
"""Adelie""","""Torgersen""",39.5,17.4,186,3800,"""FEMALE"""
"""Adelie""","""Torgersen""",40.3,18.0,195,3250,"""FEMALE"""
"""Adelie""","""Torgersen""",null,null,null,null,null
"""Adelie""","""Torgersen""",36.7,19.3,193,3450,"""FEMALE"""
…,…,…,…,…,…,…
"""Gentoo""","""Biscoe""",null,null,null,null,null
"""Gentoo""","""Biscoe""",46.8,14.3,215,4850,"""FEMALE"""
"""Gentoo""","""Biscoe""",50.4,15.7,222,5750,"""MALE"""


In [6]:
import polars as pl

# actually generated by running the following code first
# pl.Config.set_tbl_rows(8)
# pl.Config.set_fmt_str_lengths(5)
penguins = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
str,str,f64,f64,i64,i64,str
"""Adelie""","""Torgersen""",39.1,18.7,181,3750,"""MALE"""
"""Adelie""","""Torgersen""",39.5,17.4,186,3800,"""FEMALE"""
"""Adelie""","""Torgersen""",40.3,18.0,195,3250,"""FEMALE"""
"""Adelie""","""Torgersen""",null,null,null,null,null
"""Adelie""","""Torgersen""",36.7,19.3,193,3450,"""FEMALE"""
…,…,…,…,…,…,…
"""Gentoo""","""Biscoe""",null,null,null,null,null
"""Gentoo""","""Biscoe""",46.8,14.3,215,4850,"""FEMALE"""
"""Gentoo""","""Biscoe""",50.4,15.7,222,5750,"""MALE"""


In [7]:
# this is usually a non-deterministic computation
# running it multiple times will yield different results
import polars as pl

penguins = pl.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins["island"].value_counts()

island,count
str,u32
"""Biscoe""",168
"""Torgersen""",52
"""Dream""",124


In [8]:
import pandas as pd

penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE


In [9]:
import pandas as pd

# actually generated by running the following code first
# pd.set_option("display.min_rows", 8)
penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE


In [10]:
import pandas as pd

# actually generated by running the following code first
# pd.set_option("display.max_colwidth", 6)
penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE


In [11]:
import pandas as pd

# actually generated by running the following code first
# pd.set_option("display.min_rows", 8)
# pd.set_option("display.max_colwidth", 6)
penguins = pd.read_csv(
    "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv"
)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
